<?php
/** @var $block \Nsk\PartNumbersInterchange\Block\Form
 * @var Magento\Framework\Escaper $escaper
 */
?>

<div class="container-form-interchange-part-numbers">
    <form class="for-interchange-part-numbers" method="GET">

        <fieldset class="fieldset">
            <div class="field">
                <h3 id="header-label">
                    <label class="label" for="part-number-input">
                        <strong><?= $escaper->escapeHtml(__('Part Numbers Interchange')) ?></strong>
                    </label>
                </h3>
                <div class="control">
                    <input type="text" name="part_number" id="part-number-input"
                           value="<?= ($this->getRequest()->getParam('part_number') ?
                               ($escaper->escapeHtml(trim($this->getRequest()->getParam('part_number')))) : "") ?>"
                           class="input-text"/>
                </div>
            </div>
        </fieldset>
        <div class="actions-toolbar">
            <div class="actions">
                <?php if (is_string($this->getRequest()->getParam('part_number'))) : ?>
                    <a class="action primary nsk-interchange-button interchange-link-redirect"
                       href="<?= $block->getUrlClearInterchageSearch() ?>" type="button">
                        <span id="nsk-link-clear"><?= $escaper->escapeHtml(__('Clear')) ?></span>
                    </a>
                <?php else: ?>
                    <button type="reset" class="action primary nsk-interchange-button">
                        <span><?= $escaper->escapeHtml(__('Clear')) ?></span>
                    </button>
                <?php endif; ?>


                <button type="submit" class="action primary nsk-interchange-button-collation">
                        <span>
                            <?= $escaper->escapeHtml(__('Collation')) ?>
                        </span>
                </button>

            </div>
        </div>
    </form>
</div>

